### ISSUE TITLE
ascending descending style is breaking in firefox

### ISSUE THREAD

**Issue by klester** [nidhishkrishnan/ngAddRemove#1]
I was using this ngListSelect in my project and it got worked, but the only issue is that in firefox ascending descending style is breaking like as shown below

![asc](https://cloud.githubusercontent.com/assets/12235417/7531554/42a84596-f521-11e4-953d-08e54f0c646c.png)

**Comment by nidhishkrishnan** [comment]
Resolved and committed the changes, you can take the download the latest ngListSelect.js and use it in your application

**Comment by klester** [comment]
Thanks @nidhishkrishnan ...
